### PR TITLE
bumping version to 1.20.1

### PR DESCRIPTION
**Pull request by noah1510**
This simply updates the version to 1.20.1.
The mod seems to work just fine.

### CODE REVIEW

**Comment by ZestyBlaze** [comment]
Surely it's not needed anymore. Fabric API now includes its own Fake Player API

**Comment by noah1510** [comment]
It's a dependency for a different mod I updated. Since I didn't touch the logic and simply updated the api changes I have no idea if it is actually needed or how to migrate from this api to the one from fabric. 😅

**Comment by ZestyBlaze** [comment]
Unfortunately I'm not sure if CafGuild will update this API since Fabric API now has it all built in so you may have to migrate over, removes a dependency then too, shouldn't be too different honestly

**Comment by noah1510** [comment]
I tested again after downgrading the version.
The code current version (0.6.0) seems to work just fine for 1.20.1.
So I will close the PR since it does not seem like its needed.

**Pull request closed without merging**
